# MINIFORGE3 IMAGE

FROM condaforge/miniforge3:{{ conda.installer_version }} AS mf3
WORKDIR /

# BUILD IMAGE

FROM ubuntu:24.04 AS build
# Conda root
ARG CONDA_PACKAGES

# Pipeline environment snapshot definition
ARG SNAPSHOT_INPUT
ARG SNAPSHOT_PKGDIR

# Declare environment
ENV OPT=/opt
ENV HOME=/home/developer
ENV PYTHONUNBUFFERED=1
ENV DIST_PATH="${OPT}"/conda
ENV CONDA_PACKAGES="${CONDA_PACKAGES}"
ENV SNAPSHOT_INPUT="${SNAPSHOT_INPUT}"
ENV SNAPSHOT_PKGDIR="${SNAPSHOT_PKGDIR}"
ENV MAMBA_ROOT_PREFIX="${DIST_PATH}"
RUN apt update \
    && apt upgrade -y \
    && apt install -y \
        bash \
        sudo \
        build-essential \
        gfortran \
        pkgconf \
    && apt clean
SHELL ["/bin/bash", "-c"]
RUN groupadd developer \
    && useradd -m -d "$HOME" -s /bin/bash -g developer developer \
    && echo "developer:developer" | chpasswd \
    && echo "developer ALL=(ALL)	NOPASSWD: ALL" >> /etc/sudoers

# Configure Conda

# Copy the conda installation out of the official miniforge3 image
COPY --chown=developer --from=mf3 /opt/conda/ "${DIST_PATH}"

# Ensure the "conda" script can be resolved
ENV PATH="${DIST_PATH}/bin:${PATH}"

# Enable automatic initialization of the "linux" environment at run-time
RUN echo source "${DIST_PATH}"/etc/profile.d/conda.sh > /etc/profile.d/conda.sh \
    && \
        if [[ -x "${MAMBA_ROOT_PREFIX}"/bin/mamba ]]; then \
            "${MAMBA_ROOT_PREFIX}"/bin/mamba shell init --shell bash --dry-run \
            | (ignore=1; \
                while read line; do \
                    if [[ "$line" == "#"* ]]; then ignore=0; fi; \
                    if (( ignore == 0 )); then echo $line; fi; \
                done) >> /etc/profile.d/conda.sh; \
        fi \
    && source /etc/profile.d/conda.sh \
    && echo conda activate linux > /etc/profile.d/zconda.sh

# Install the delivery snapshot
USER developer
WORKDIR "${HOME}"
ADD --chown=developer "${SNAPSHOT_INPUT}" "${HOME}/SNAPSHOT.yml"
ADD --chown=developer "${SNAPSHOT_PKGDIR}" "${HOME}/packages"
RUN conda config --set auto_update_conda false \
    && conda config --set always_yes true \
    && conda config --set quiet true \
    && conda config --set rollback_enabled false \
    && sed -i -e "s|@CONDA_CHANNEL@|${HOME}/packages/conda|;s|@PIP_ARGUMENTS@|--extra-index-url file://${HOME}/packages/wheels|;" SNAPSHOT.yml \
    && if [ -n "${CONDA_PACKAGES}" ]; then mamba install ${CONDA_PACKAGES}; fi \
    && mamba env create -n linux --file SNAPSHOT.yml \
    && find "${DIST_PATH}" -follow -type f -name '*.a' -delete \
    && find "${DIST_PATH}" -follow -type f -name '*.pyc' -delete \
    && conda clean --force-pkgs-dirs --all --yes \
    && rm -rf ${HOME}/.cache \
    && rm -rf ${HOME}/packages \
    && rm -rf /tmp/* \
    && rm -rf /var/tmp/*

# FINAL IMAGE

FROM ubuntu:24.04

# Declare environment
ENV OPT=/opt
ENV HOME=/home/developer
ENV PYTHONUNBUFFERED=1
ENV DIST_PATH="${OPT}"/conda
ENV MAMBA_ROOT_PREFIX="${DIST_PATH}"

# Install the bare minimum software required
RUN apt update \
    && apt upgrade -y \
    && apt install -y \
        bash \
        sudo \
        tini \
    && apt clean
COPY --chown=root --from=build /etc/ /etc
COPY --chown=developer --from=build /opt/conda "${DIST_PATH}"
COPY --chown=developer --from=build /home/developer/ "${HOME}"
USER developer
WORKDIR "${HOME}"
ENTRYPOINT ["tini", "--"]
CMD ["/bin/bash", "-l"]
